services:
  redis-dev:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - my_custom_network

  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_custom_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-dev
    networks:
      - my_custom_network
    volumes:
      - ./tmp/pgadmin_data:/var/lib/pgadmin

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      REDIS_HOSTS: "local:redis-dev:6379"
    ports:
      - "8081:8081"
    depends_on:
      - redis-dev
    networks:
      - my_custom_network

 
networks:
  my_custom_network:
    driver: bridge
